### ISSUE TITLE
sql中的id不自增，id是自定义的列表，并添加了@TableId，配置idType为auto，input等都不生成

### ISSUE THREAD

**Issue by li-xiaojun** [baomidou/mybatis-plus#2010]
### 当前使用版本(必须填写清楚，否则不予处理)

版本：3.3.0

### 该问题是怎么引起的？**([最新版](https://search.maven.org/search?q=g:com.baomidou%20a:mybatis-*)上已修复的会直接**close**掉)**
创建表的sql没有指定自增，id为自定义的列表，比如User表id为user_id，已经添加了@TableId注解，通过全局配置和类字段都依次配置了auto，input等，就是提示user_id不能为空，没法自动生成id

### 重现步骤
```
@Data
@NoArgsConstructor
@TableName("t_fdt")
public class FamilyDoctor extends BaseDomain {
    private long creator_id;
    @TableId(type = IdType.AUTO)
    private Long fdt_id;
    private String head_portrait;
    private int member_num;
    private long operator_id;
    private int service_times;
    private String team_introduction;
    private String team_name;
}
```
yml配置：
```yml
  # mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
```
