### ISSUE TITLE
updateBatchById批量更新报空指针异常

### ISSUE THREAD

**Issue by 112921482** [baomidou/mybatis-plus#2542]
### 当前使用版本(必填,否则不予处理)
3.3.2

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
使用updateBatchById，集合为2197条数据，报错。

将2197条数据遍历使用updateById，则正常。
将日志调整为debug级，使用updateBatchById查看生成的sql，将sql直接在数据库运行也正常。

### 报错信息
Cause: java.sql.BatchUpdateException: java.lang.NullPointerException

**Comment by lucheng** [comment]
你这个我用3.3.2版本 也没复现

**Comment by miemieYaho** [comment]
有复现demo?

**Comment by 112921482** [comment]
大概定位到问题，并不是数量的问题。使用mysql数据库，表中有一个字段类型为date，对应entity的类型为LocalDate，如果该字段保存值，则报错，不保存的话updateBatchById不会保存，只有一条数据的时候也是如此，

**Comment by miemieYaho** [comment]
那就是驱动问题,不支持jdbc4,mybatis底层全面升级为jdbc4了

**Comment by 112921482** [comment]
那我现在要怎么解决呢？

**Comment by 112921482** [comment]
问题是，我单独使用updateById不会报错，只有在使用updateBatchById才报错，这也是因为驱动问题吗？

**Comment by 112921482** [comment]
问题是，我单独使用updateById不会报错，只有在使用updateBatchById才报错，这也是因为驱动问题吗？

**Comment by lucheng** [comment]
本地也没复现，你把你的核心问题代码  发出来。  数据库是mysql吧，  字段date   属性是localdate 对吧

**Comment by 112921482** [comment]
`   
 @Test
    void batchUpdateTest1() {
        List<PortalUser> portalUserList = portalUserService.list();
        portalUserList.forEach(portalUser -> portalUser.setRealName(LocalDateTime.now().toString()));
        portalUserService.updateBatchById(portalUserList);
}
`
`    @Test
    void batchUpdateTest12() {
        List<PortalUser> portalUserList = portalUserService.list();
        portalUserList.forEach(portalUser -> {
            portalUser.setRealName(LocalDateTime.now().toString());
            portalUser.setBirthday(LocalDate.now());
        });
        portalUserService.updateBatchById(portalUserList);
    }`
两个测试，第一个测试不设置生日可以通过，第二个设置则报错，数据库mysql，版本5.7.30

**Comment by miemieYaho** [comment]
驱动版本?

**Comment by 112921482** [comment]
springboot项目，springboot版本：2.3.0，mysql版本：8.0.20

**Comment by miemieYaho** [comment]
pom里和mybatis有关的都有啥?

**Comment by 112921482** [comment]
<dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.2</version>
        </dependency>

**Comment by miemieYaho** [comment]
去掉，只保留mp的

**Comment by 112921482** [comment]
去掉了，还是报错

**Comment by miemieYaho** [comment]
那你整个复现demo吧

**Comment by 112921482** [comment]
[demo.zip](https://github.com/baomidou/mybatis-plus/files/4716937/demo.zip)

**Comment by 112921482** [comment]
我用这个demo可以成功复现，复现的代码在测试类中，使用的数据库是mysql5.7.30

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/83528252-7858b180-a51b-11ea-94e3-e7c53dbfc82d.png)
没毛病啊

**Comment by 112921482** [comment]
要不链我的测试库试试？我数据库就报错啊

**Comment by miemieYaho** [comment]
```yml
data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
```
你这一坨配置的问题.搞不懂啥意思就别乱配,over
