### ISSUE TITLE
mybatis-plus-boot-starter：3.2.0 insert方法主键id未返回

### ISSUE THREAD

**Issue by mouday** [baomidou/mybatis-plus#3146]
### 当前使用版本(必填,否则不予处理)

配置
```yml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

  global-config:
      db-config:
        # 主键类型
        id-type: auto
        table-prefix: "mo"

```
```xml
<dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.2.0</version>
</dependency>
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

```java
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.util.Date;

@Data
public class User {
    @TableId(type = IdType.AUTO)
    private Integer id;

    private String name;

    private String dynasty;

    // 诗词数量， 排除字段
    @TableField(exist = false)
    private Integer count;

    private Date lastLoginTime;

    private Date createTime;

    private Date updateTime;

}
```

```java
public interface UserMapper extends BaseMapper<User> {
}
```

```java
User user = new User();
user.setName("李小白");
user.setDynasty("明朝");

UserMapper.insert(user);
```

### 报错信息
没有报错，参考了issues里边，都是说可以直接返回id,可是我的没有返回主键ID
