### ISSUE TITLE
mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap

### ISSUE THREAD

**Issue by randolph555** [baomidou/mybatis-plus#3469]
### 当前使用版本(必填,否则不予处理)
3.1.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
没有操作CURD，只是nacos触发了动态刷新

### 报错信息
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'mybatis-plus.configuration.result-maps[0]' to org.apache.ibatis.mapping.ResultMap

**Comment by 986510453** [comment]
@randolph555 请问是否已解决？

**Comment by qmdx** [comment]
无法重现测试

**Comment by jervainy** [comment]
我也出现这个问题了，Spring Boot 2.2.0.RELEASE，mybatis-plus-boot-starter 3.5.1,使用的nacos，应用启动时就会报错，mybatis plus配置如下:
```
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml,classpath:/mapper/dm/*Mapper.xml
  typeAliasesPackage: com.songcan.model.oauth
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
    refresh: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
```
