### ISSUE TITLE
3.0beta 逻辑删除查询问题

### ISSUE THREAD

**Issue by masteranthoneyd** [baomidou/mybatis-plus#387]
启用逻辑删除之后 select 语句异常：
```
### SQL: SELECT id AS id,date,name,remark,is_del AS isDel,status,create_time,update_time FROM flash_sale WHERE id=? is_del=1
```
is_del 前面少了个 AND

application配置：
```
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.youngboss.flashsale.domain.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      db-type: mysql
      logic-delete-value: 0
      logic-not-delete-value: 1
    refresh: true
#    sql-injector: com.youngboss.flashsale.config.MyLogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
```
实体字段：
```
@TableField(value = "is_del")
@TableLogic
private Integer isDel;
```
bean配置
```
@Bean
public ISqlInjector logicSqlInjector() {
	return new LogicSqlInjector();
}
```
