### ISSUE TITLE
SpringBoot + MyBatis-Plus + PostgreSQL + 全大写时找不到字段

### ISSUE THREAD

**Issue by wltj920** [baomidou/mybatis-plus#3935]
### 当前使用版本(必填,否则不予处理)
3.4.3.3

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
PostgreSQL数据库，Mybatis-Plus在配置`capital-mode: true`和`column-format: "\"%s\""` 后，生成的SQL语句仍然不带双引号，导致大写的数据库字段查不出来

### 重现步骤(如果有就写完整)
1. 使用PostgreSQL数据库
2. 配置Mybatis-Plus：
```yaml
mybatis-plus:
  # mapper.xml文件的路径
  mapper-locations: classpath:/mapper/module/*/*.xml
  global-config:
    db-config:
      capital-mode: true # 开启全局大写命名，表名和字段名都生效
      column-format: "\"%s\""
```
3. 配置实体类：
```java
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName(value = "SYS_ORGANI")
@ApiModel("系统组织结构表")
@ExcelModel(includeAllField = false, excludeParent = true)
public class Organi extends Model<Organi> {

    private static final long serialVersionUID = 1L;

    /**
     * 组织ID
     */
    @TableId(value = "ORGANI_ID", type = IdType.ASSIGN_ID)
    @ApiModelProperty(value = "组织ID", example = "1")
    @ExcelColumn(title = "组织ID")
    private String organiId;

    /**
     * 组织名称
     */
    @TableField("ORGANI_NAME")
    @ApiModelProperty(value = "组织名称")
    @ExcelColumn(title = "组织名称")
    private String organiName;
}
```

### 报错信息
```shell
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT ORGANI_ID, ORGANI_NAME, ORGANI_SIMPLE_NAME, ORGANI_REGION_ID, ORGANI_DESCRIPTION, ORGANI_PARENT_ID, ORGANI_TYPE_ID, ORGANI_RANK, ORGANI_STRUCTURE, ORGANI_CREATE_DATE, ORGANI_UPDATE_DATE, ORGANI_CREATE_USER_ID, ORGANI_UPDATE_USER_ID, ORGANI_SORT, ORGANI_LEAF, ORGANI_DISPLAY, ORGANI_STATUS, ORGANI_CODE, ORGANI_REMARK, ORGANI_ENG_NAME, ORGANI_ENG_SIMPLE_NAME FROM SYS_ORGANI WHERE ORGANI_ID = ?
### Cause: org.postgresql.util.PSQLException: ERROR: relation "sys_organi" does not exist
  位置：371
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "sys_organi" does not exist
```

**Comment by miemieYaho** [comment]
![image](https://user-images.githubusercontent.com/28334419/133881837-2927c675-07c5-4ce1-9368-5abb8f81e483.png)
![image](https://user-images.githubusercontent.com/28334419/133881845-fb6fce8b-b2a6-4a78-a51f-a88853dc1cc1.png)

**Comment by xlgo** [comment]
![image](https://user-images.githubusercontent.com/8422903/162975706-659e6fc6-5d77-45b7-80a6-2eeb4cd6f0f2.png)
配置上去还是找不到。。。。

``` entity
   @TableField(value = "Name", keepGlobalFormat = true)
    private String Name;
```
``` yaml
mybatis-plus:
  global-config:
    db-config:
      capital-mode: true
      column-format: "\"%s\""
```
