### ISSUE TITLE
多数据源时向主库插入数据未能提交

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [baomidou/mybatis-plus#4269]
```
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.0</version>
</dependency>
<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
    <version>3.2.1</version>
</dependency>
```
配置：
```
  datasource:
    dynamic:
      primary: database-a
      strict: true
      datasource:
        database-a:
          url: jdbc:mysql://192.168.24.201:3306/database_a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        database-b:
          url: jdbc:mysql://192.168.24.201:3306/database_b?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
```

相关代码
```
    @Resource
    TestTableService testTableService;

    @Test
    @Transactional(rollbackFor = Exception.class)
    public void testSave() {
        List<TestTable> list = testTableService.list();
        System.out.println(JSONObject.toJSONString(list));

        TestTable testTable= new TestTable();
        testTable.setContent("这是一个保存测试");

        testTableService.save(testTable);
    }
```

重现方法：
1. 使用mybatis-plus-generator生成的数据库表相关代码
2. 开启事务直接向主库的test_table表插入一行数据
3. 数据写入成功，但是未能提交
