### ISSUE TITLE
PostgreSQL  字段名大写 异常

### ISSUE THREAD

**Issue by xlgo** [baomidou/mybatis-plus#4428]
![image](https://user-images.githubusercontent.com/8422903/162975706-659e6fc6-5d77-45b7-80a6-2eeb4cd6f0f2.png)
配置上去还是找不到。。。。

``` entity
   @TableField(value = "Name", keepGlobalFormat = true)
    private String Name;
```
``` yaml
mybatis-plus:
  global-config:
    db-config:
      capital-mode: true
      column-format: "\"%s\""
```

_Originally posted by @xlgo in https://github.com/baomidou/mybatis-plus/issues/3935#issuecomment-1096746995_
