### ISSUE TITLE
建议把官网的表格MAX-WIDTH改一下

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [baomidou/mybatis-plus#4515]
```css
.theme-default-content:not(.custom) {
    max-width: 1000px;
...
}
```

请将上面样式的max-width改一下,否则,将导致下面的情况

![Snipaste_2022-05-22_18-59-41](https://user-images.githubusercontent.com/24890682/169691932-1301fd9a-87f8-4acd-8d2c-7d98a3a060c2.jpg)
