### ISSUE TITLE
自定义sql表名前缀配置不生效

### ISSUE THREAD

**Issue by lijunyong** [baomidou/mybatis-plus#4679]
### 当前使用版本(必填,否则不予处理)
```
<dependency>
         <groupId>com.baomidou</groupId>
         <artifactId>mybatis-plus-boot-starter</artifactId>
          <version>3.4.3</version>
</dependency>
```

### 该问题是如何引起的？(确定最新版也有问题再提!!!)

在做从mysql向gaussdb迁移的时候发现sql必须加上模式名

### 重现步骤(如果有就写完整)
```
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration-properties:
    prefix: test1.   #不生效
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
      table-prefix: test1.   #是生效的
```
