### ISSUE TITLE
QueryWrapper条件查询SelectCount为0，SelectOne为NULL，SelectList为[]

### ISSUE THREAD

**Issue by RedCrazyGhost** [baomidou/mybatis-plus#4918]
### 当前使用版本(必填,否则不予处理)
mybatis-plus version : 3.5.1
mysql : 8.0.30
springboot : 2.6.11

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
我不确定是否是我的使用方法有误，还望指正。

### 重现步骤(如果有就写完整)
执行测试代码如下：
![image](https://user-images.githubusercontent.com/49381700/199420336-bda96265-15a1-4950-8c8e-d875636cad68.png)

数据库内数据如下：
![image](https://user-images.githubusercontent.com/49381700/199420429-e4d40eb8-6332-4c12-af62-43f68e1b23cf.png)

```
@Data
@NoArgsConstructor
@TableName(value="tags",autoResultMap = true)
public class Tag implements Serializable {

    /**
     * 标签ID
     */
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     * 标签名字
     */
    private String name;

    /**
     * 创建时间
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createTime;

    /**
     * 文章ID列表
     */
    @TableField(typeHandler = ObjectToJson.class)
    private List<Note> noteIdList;

    /**
     * 是否逻辑删除
     */
    @TableLogic
    private Integer isDelete;

    @TableField(exist = false)
    private static final long serialVersionUID =51235L;

    public Tag(String name){
        this.name=name;
    }
}
```

测试执行结果如下：
![image](https://user-images.githubusercontent.com/49381700/199420526-ffac6080-2e0d-4b65-a627-37e213442da9.png)

### 报错信息
如果SelectOne正常查找到的数据的话会报错，毕竟数据库中有多条数据。

**Comment by miemieYaho** [comment]
你连错库了吧,执行sql和结果封装都是mybatis的事

**Comment by RedCrazyGhost** [comment]
你好，我用是本地docker的mysql容器

Docker version 20.10.20, build 9fdeb9c

![image](https://user-images.githubusercontent.com/49381700/199432713-031b0426-a894-41e7-89b7-c454f76a30eb.png)

下方为数据相关配置：
```yaml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1
```
