### ISSUE TITLE
分布式id怎么使用啊

### ISSUE THREAD

**Issue by forezp** [baomidou/mybatis-plus#51]
我的全局设置

```
mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.xiaoantimes.taichi.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

```
实体设置：

```
@TableName("sys_user")
public class SysUser extends Model<SysUser> {

    private static final long serialVersionUID = 1L;

    /**
     * 用户编号
     */
	@TableId(value="id", type= IdType.ID_WORKER)
	private long id;
    /**
```
插入的时候，没有生产id ，请问该怎么做？
