### ISSUE TITLE
service.save()  Invalid bound statement (not found)

### ISSUE THREAD

**Issue by pencilso** [baomidou/mybatis-plus#550]
### 当前使用版本(必须填写清楚，否则不予处理)
mybatis-plus-boot-starter
3.0.1

### 该问题是怎么引起的？(请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!)
调用service的save方法引起的

### 重现步骤
每次必现

### 报错信息
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.xxxx.db.mapper.TopicModelMapper.insert
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:227)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:49)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy108.insert(Unknown Source)
	at com.yscall.kulaidian.db.service.impl.TopicServiceImpl.addTopic(TopicServiceImpl.java:37)
	at com.yscall.kulaidian.db.service.impl.TopicServiceImpl$$FastClassBySpringCGLIB$$4b778966.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at

**Comment by pencilso** [comment]
大兄弟  着急啊  能不能帮忙看看

**Comment by pencilso** [comment]
不太可能  我在没用plus之前 一直好好的  现在没用plus的mapper都正常  继承了BaseMapper的mapper 就不正常  会报这个错

**Comment by pencilso** [comment]
算了  这东西我还是无福消受  我还是用我的Mybatis吧

**Comment by qmdx** [comment]
http://mp.baomidou.com/

https://gitee.com/baomidou/mybatis-plus-samples

https://gitee.com/baomidou/mybatisplus-spring-boot

**Comment by pencilso** [comment]
文档看了好几遍了  不行

**Comment by qmdx** [comment]
http://mp.baomidou.com/guide/faq.html#%E5%87%BA%E7%8E%B0-invalid-bound-statement-not-found-%E5%BC%82%E5%B8%B8

**Comment by pencilso** [comment]
非plus的mapper 和 plus的mapper是在同一个包下  mapper肯定是能扫描到的 非plus 的mapper是可以正常使用的  但是plus的mapper 插入就报错

**Comment by qmdx** [comment]
好好看看我发的那些连接，问题就是配置这块，没有自动注入。

**Comment by pencilso** [comment]
项目是SpringBoot 2.0
这个配置按文档上加了 
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
然后不行  我又尝试更改为我之前用Mybatis的配置 改成如下了
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
也还是不行

再然后 MapperScan注解也配置了  我可以肯定 绝对配置的是mapper的包名
而且同一个包下的非plus mapper正常、

不是maven多模块项目
表名叫topic 命名空间应该不会又问题

**Comment by pencilso** [comment]
而且官方的Mybatis maven被我删了  只留下
 <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>

**Comment by qmdx** [comment]
```

# 参考 配置
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.baomidou.ant.*.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      column-like: true
```
