### ISSUE TITLE
mysql表主键 ID 重复

### ISSUE THREAD

**Issue by phial3** [baomidou/mybatis-plus#6332]
**当前使用版本**
java8 + spring-boot:2.7.18 + mybatis-plus:3.5.7

**当前环境信息**
例如: Java8 + Mysql8.0

**描述bug现象**
<img width="1151" alt="image" src="https://github.com/baomidou/mybatis-plus/assets/27754514/5a280cff-e422-4795-8b40-b76511a8b26c">

**提供问题复现步骤**
使用默认自动生成 ID 的方式，生产环境报主键冲突错误，初步考虑是不是因为在并发环境下产生的，本地没出现

**提供完整堆栈日志(可选)**

**提供问题复现工程(可选)**
请尽量提供复现工程,减少大家排错的时间.

**Comment by miemieYaho** [comment]
https://github.com/baomidou/mybatis-plus/issues/6055

**Comment by phial3** [comment]
mybatis-plus配置如下：
```yaml
mybatis-plus:
  mapper-locations: "classpath*:/mapper/*.xml"
  check-config-location: true
  global-config:
    enable-sql-runner: true
    db-config:
      id-type: assign_id
      logic-delete-field: "deleted"
      logic-delete-value: true
      logic-not-delete-value: false
      insert-strategy: always
      update-strategy: not_null
      where-strategy: not_null
    sequence:
      worker-id: ${WORKER_ID:${random.int(31)}}
      datacenter-id: ${DATACENTER_ID:${random.int(31)}}
      preferred-networks: "${PREFERRED_NETWORKS:127.0.0.1}"
      ignored-interfaces: "${IGNORED_INTERFACES:lo,docker0}"
```

已经配置了workId和datacenterId，可以看到生效了，并且只有一个实例，为什么今天还是发现有主键重复问题
