### ISSUE TITLE
Enum 映射 变量对应数据库表字段名称不同  @TableField 修改无效

### ISSUE THREAD

**Issue by craone** [baomidou/mybatis-plus#646]
### 当前使用版本(必须填写清楚，否则不予处理)

```groovy
compile("com.baomidou:mybatis-plus-boot-starter:3.0.5-SNAPSHOT")
```

### 该问题是怎么引起的？**(注意!!!请使用最新版(具体版本查看CHANGELOG.md),如还有该问题再提 issue!,否则直接拒绝,毫不商量!!!)**
这样映射成功
```kotlin
var roleId: RoleEnum? = null,
```

这样映射失败
```
@TableField(value = "role_id")
var role: RoleEnum? = null,
```

### 重现步骤

哈，映射配置按照教程都成功，只是改一下变量名称不成功，我还以为不需要重现步骤呢哈！

`application.yml`已配置
```yml
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.model
  typeEnumsPackage: com.model.enums
  type-handlers-package: com.handlers.type
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: MYSQL
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    lazy-load-trigger-methods: equals,clone,hashCode,toString
```
实体类
```kotlin
        @TableField(value = "role_id")
        var role: RoleEnum? = null,
        var statusId: StatusEnum? = null,
```
`RoleEnum`类
```kotlin
enum class RoleEnum(private val value: Int, val desc: String)  : IEnum<Int> {
    USER(0b00000001, "用户"),
    SALESMAN(0b00000010, "业务员"),
    ADMIN(0b00000100, "管理员");
    override fun getValue(): Int {
        return this.value
    }
}
```
`StatusEnum`类
```kotlin
enum class StatusEnum(private val value: Int, val desc: String) : IEnum<Int> {
    INVALID(0b00000000, "无效"),
    NORMAL(0b00000001, "正常");

    override fun getValue(): Int {
        return this.value
    }
}
```
### 报错信息

`role` 对象`enum`不进来，实际上数据库字段名称为 `role_id`，如果变量名称改为`roleId`映射成功
`statusId`是映射成功
