### ISSUE TITLE
配置逻辑删除功能后, 后续所有查询默认都会加上where deleted = 0 过滤条件

### ISSUE THREAD

**Issue by jingTian-z** [baomidou/mybatis-plus#6746]
### 确认

- [x] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [x] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [x] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

文档的功能对逻辑删除的功能描述如下：
<img width="730" alt="Image" src="https://github.com/user-attachments/assets/373508c1-313b-43b7-b7a0-e8adf5612a04" />

在查询时是否需要过滤deleted=0 的记录 ，希望是可以配置的。 有些业务需要对deleted=0的记录进行查询。
比如可以增加'logic-query-deleted' 配置，满足不同的业务需求。
```
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-query-deleted: false
```
