### ISSUE TITLE
[功能改进]: mysql 8 ，逻辑删除 如何使用datetime

### ISSUE THREAD

**Issue by zuihou** [baomidou/mybatis-plus#6795]
### 确认

- [x] 我的版本是最新版本, 我的版本号与 [version](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.baomidou%22%20AND%20a%3A%22mybatis-plus%22) 相同, 并且项目里无依赖冲突
- [x] 我已经在 [issue](https://github.com/baomidou/mybatis-plus/issues) 中搜索过, 确认问题没有被提出过
- [x] 我已经修改标题, 将标题中的 描述 替换为遇到的问题

### 功能改进

MySQL 8.0 逻辑删除 希望使用 datetime ，如何与唯一索引同时使用？
1. 实体类
```
public class User {

    @TableField(value = "deleted_at")
    private LocalDateTime deletedAt;
}

```
2. sql
<img width="975" alt="Image" src="https://github.com/user-attachments/assets/52634d6d-f654-435f-8204-34c9fe7477fb" />

3. 配置
```
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deletedAt # 全局逻辑删除字段名
      logic-delete-value: now() # 逻辑已删除值
      logic-not-delete-value: 'null' # 逻辑未删除值
```

在mysql 8 中， 我对 config_key 和 deleted_at 创建了唯一索引，但因为  deleted_at 设置为 null ，表示未删除， 所以唯一索引就失效了

<img width="1021" alt="Image" src="https://github.com/user-attachments/assets/66ee61ef-77bf-4423-8391-bb3213242dd6" />
